version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4000:80
    volumes:
      - ./app:/app
    depends_on:
      - dbc
  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=mysecretpassword
      - MYSQL_DATABASE=myappdb
      - MYSQL_USER=myappuser
      - MYSQL_PASSWORD=myapppassword
    volumes:
      - dbdata:/var/lib/mysql
volumes:
  dbdata:
